



#科技路附近SDK舒服多了德生科技发链接多斯拉克发多少六氟化硫的时间里看电视剧福克斯来得及发
#松岛枫葫芦岛市会计分录快速搭建
《信息网络传播权保护条例》第2条明确规定，在网络环境下，使用他
人作品原则上应当取得著作权人的授权许可，但是对于法定许可的规定是十分有限的。在
目前复杂多变的信息网络环境下，网络作品的数量及其繁杂，而我国现行立法又没有关于著
作权公示制度的相关规定，因此在网络环境下，建立健全行之有效的许可模式，尤其是进一
步明确法定许可的有关规定，是非常迫切并十分必要的。论及法定许可在网络环境下的适用时，
上海大学的陶鑫良教授曾乐观预言，法定许可应当成为网上传播一般作品的新的国际惯例，
但是在西南政法大学举办的著作权法基础理论研讨会上，国家版权局法规司于慈珂司长在
介绍我国著作权法修改的进展时指出，著作权法定许可已经面临生死存亡的危机。可见对于法
定许可在网络环境中的适用问题
，无论是学界还是实务部门，都有着很大的争议与分歧。